### ISSUE TITLE
QubitUnitary throwing exception for wavefunction simulators

### ISSUE THREAD

**Issue by soudy** [PennyLaneAI/pennylane-forest#22]
When using `QubitUnitary` with `forest.numpy_wavefunction` or `forest.wavefunction`, an exception gets thrown. The program
```python
import numpy as np
import pennylane as qml

dev_numpy = qml.device('forest.numpy_wavefunction', wires=1)

U = np.array([[0, 1], [1, 0]])

@qml.qnode(dev_numpy)
def circuit():
    qml.QubitUnitary(U, wires=0)
    return qml.expval(qml.PauliZ(0))

print(circuit())
```

Gives the following exception:
```
Traceback (most recent call last):
  File "/tmp/test3.py", line 13, in <module>
    print(circuit())
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pennylane/decorator.py", line 153, in wrapper
    return qnode(*args, **kwargs)
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pennylane/qnode.py", line 609, in __call__
    return self.evaluate(args, **kwargs)  # args as one tuple
  File "/home/soud/anaconda3/lib/python3.7/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pennylane/qnode.py", line 682, in evaluate
    ret = self.device.execute(self.queue, self.ev, self.variable_ops)
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pennylane/_device.py", line 223, in execute
    self.pre_measure()
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pennylane_forest/numpy_wavefunction.py", line 62, in pre_measure
    self.state = self.qc.execute(self.prog).wf_simulator.wf.flatten()
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pyquil/pyqvm.py", line 451, in execute
    halted = self.transition()
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pyquil/pyqvm.py", line 284, in transition
    self.wf_simulator.do_gate(gate=instruction)
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pyquil/numpy_simulator.py", line 268, in do_gate
    gate_matrix, qubit_inds = _get_gate_tensor_and_qubits(gate=gate)
  File "/home/soud/anaconda3/lib/python3.7/site-packages/pyquil/numpy_simulator.py", line 164, in _get_gate_tensor_and_qubits
    matrix = QUANTUM_GATES[gate.name]
KeyError: 'U_970c9036'
```

I think the Forest wavefunction simulators don't support arbitrary unitaries, but I haven't looked into it much further. It _does_ work for the QVM simulator. Perhaps this should throw an exception about `QubitUnitary` not being supported if that's the case.

**Comment by soudy** [comment]
Hey @josh146, I'm using PyQuil 2.11.0, and Penny Lane 0.5.0. Haven't installed QVM and Quilc yet as I was just testing the wavefunction simulators.

**Comment by josh146** [comment]
I've had a look, and this seems to be an issue specifically with the NumPy wavefunction - I've made an issue over at the PyQuil repository: https://github.com/rigetti/pyquil/issues/1059

**Comment by antalszava** [comment]
Closing as this was resolved (script runs correctly).
